test_that("the offline catalog names every managed survey and its minimum", {
  mock_local()
  catalog<-endomer_packages();x<-endomer_deps()
  expect_identical(catalog$package,c("enftr","encftr","enhogar","engihr"))
  expect_identical(catalog$required,c("0.9.0","0.10.0","0.5.0","0.3.0"))
  expect_identical(x$package,catalog$package)
  expect_true(all(x$meets_requirement));expect_false(any(x$behind))
  expect_identical(x$status,rep("meets_minimum",4))
  expect_true(all(is.na(x$cran)));expect_true(all(is.na(x$loaded)))
  expect_identical(x$action,rep("none",4))
  expect_identical(x$source,rep("bundled_minimum",4))
  expect_identical(endomer_deps(),x)
})
test_that("numeric version ordering and missing packages produce actionable states", {
  db<-fixture(c("0.8.0","0.9.0","0.5.0","0.3.0"));db<-db[1:2,]
  mock_local(db)
  x<-endomer_deps()
  expect_identical(x$status,c("below_minimum","below_minimum","not_installed","not_installed"))
  expect_identical(x$action,c("update","update","install","install"))
  expect_true(all(x$behind));expect_false(any(x$meets_requirement))
  expect_true(is.na(x$local[3]))
})
test_that("an index need not contain the metapackage or every survey", {
  mock_local()
  index<-data.frame(Package=c("enftr","encftr"),Version=c("0.9.0","0.11.0"))
  x<-endomer_deps(available=index)
  expect_identical(x$package,c("enftr","encftr","enhogar","engihr"))
  expect_identical(x$status,c("current","update_available","unavailable","unavailable"))
  expect_identical(x$behind,c(FALSE,TRUE,NA,NA))
  expect_identical(x$action,c("none","update","resolve_source","resolve_source"))
  expect_identical(x$target,x$cran)
  expect_identical(x$source,rep("supplied_index",4))
  empty<-index[0,];y<-endomer_deps(available=empty)
  expect_true(all(is.na(y$behind)));expect_identical(y$status,rep("unavailable",4))
})
test_that("older repositories never recommend a downgrade or an unusable upgrade", {
  mock_local()
  x<-endomer_deps(available=fixture(c("0.8.0","0.10.0","0.5.0","0.3.0")))
  expect_identical(x$status[1],"repository_below_minimum")
  expect_identical(x$action[1],"resolve_source");expect_false(x$target_compatible[1])
  expect_false(x$behind[1])
  mock_local(fixture(c("1.0.0","0.10.0","0.5.0","0.3.0")))
  y<-endomer_deps(available=fixture())
  expect_identical(y$status[1],"newer_than_target");expect_identical(y$action[1],"none")
})
test_that("loaded versions are distinguished from versions on disk", {
  mock_local(loaded=function(package) if(package=="enhogar") "0.3.0" else NA_character_)
  x<-endomer_deps()
  expect_identical(x$restart_required,c(FALSE,FALSE,TRUE,FALSE))
  expect_identical(x$action[3],"restart_session")
  expect_identical(x$loaded[3],"0.3.0");expect_identical(x$local[3],"0.5.0")
})
test_that("recursive reports follow mandatory graph edges and terminate cycles", {
  db<-fixture();db$Imports<-c("extA, stats",NA,NA,NA)
  extra<-.endomer_index(data.frame(Package=c("extA","extB","stats"),Version=c("1.0","2.0","4.5.1"),
    Imports=c("extB, missingDep","extA",NA),Priority=c(NA,NA,"base")))
  db<-rbind(db,extra[names(db)]);db$Suggests<-"optionalOnly"
  mock_local(db)
  x<-endomer_deps(recursive=TRUE)
  expect_setequal(x$package,c("enftr","encftr","enhogar","engihr","extA","extB","missingDep"))
  expect_false(any(c("R","stats","optionalOnly") %in% x$package))
  expect_true(all(is.na(x$required[x$package %in% c("extA","extB")])) )
  expect_true(all(x$status[x$package %in% c("extA","extB")]=="installed_unchecked"))
  expect_identical(x$action[x$package=="missingDep"],"resolve_source")
  index<-fixture();index$Imports<-c("newDep",NA,NA,NA)
  y<-endomer_deps(recursive=TRUE,available=index)
  expect_true("newDep" %in% y$package);expect_false("extA" %in% y$package)
})
test_that("invalid requests and malformed indices fail clearly", {
  mock_local()
  for(v in list(NA,1,"TRUE",c(TRUE,FALSE))) {
    expect_error(endomer_deps(recursive=v),"recursive")
    expect_error(endomer_update(quiet=v),"quiet")
  }
  for(v in list(NA,1,"@CRAN@",character(),"")) expect_error(endomer_deps(repos=v),"repos")
  expect_error(endomer_deps(repos="https://example.invalid",available=fixture()),"not both")
  expect_error(endomer_deps(available=list()),"available")
  expect_error(endomer_deps(available=data.frame(Package="enftr")),"Version")
  for(v in c(NA,"","1.x","v1.0"))
    expect_error(endomer_deps(available=data.frame(Package="enftr",Version=v)),"Version")
  expect_error(endomer_deps(available=rbind(fixture(),fixture())),"unique")
  expect_error(endomer_deps(lib.loc=NA_character_),"lib.loc")
})
test_that("update is a read-only report with accurate messages", {
  mock_local()
  before<-search();opts<-getOption("repos")
  result<-withVisible(endomer_update(quiet=TRUE))
  expect_false(result$visible);expect_equal(result$value,endomer_deps())
  expect_output(expect_message(endomer_update(),"no se consulto Internet"),NA)
  expect_identical(search(),before);expect_identical(getOption("repos"),opts)
  expect_error(endomer_deps(repos="https://example.invalid"),"Unexpected network")
  local_mocked_bindings(.endomer_available=function(repos) fixture(),.package="endomer")
  x<-endomer_deps(repos="https://example.invalid")
  expect_identical(x$status,rep("current",4));expect_identical(x$source,rep("repository_index",4))
})
