source("endomer/scripts/bootstrap.R")
workspace<-normalizePath(".",winslash="/")
out<-normalizePath(Sys.getenv("ENDOMER_RELEASE_DIR","artifacts/endomer-engih-release"),winslash="/")
script<-file.path(out,"bundle/install.R")
rscript<-file.path(R.home("bin"),"Rscript.exe")
for(type in c("win.binary","source")) {
  lib<-file.path(out,if(type=="source") "install-source" else "install-binary")
  log<-file.path(out,paste0("install-",if(type=="source") "source" else "binary",".log"))
  status<-system2(rscript,c(shQuote(script),shQuote(lib),type),stdout=log,stderr=log)
  if(status!=0L)stop("Bundle installation failed: ",log)
  cat("Verified seven-package installation:",type,"\n")
}
# Corrupted archives and absent prerequisites must fail before creating a library.
bad<-file.path(out,"preflight-fixture");dir.create(file.path(bad,"packages/r"),recursive=TRUE,showWarnings=FALSE)
file.copy(script,file.path(bad,"install.R"),overwrite=TRUE)
inventory<-read.dcf(file.path(out,"bundle/packages.dcf"))
for(n in inventory[,"Binary"])writeLines("corrupted test fixture",file.path(bad,"packages/r",n))
write.dcf(inventory,file.path(bad,"packages.dcf"))
writeLines(character(),file.path(bad,"external-dependencies.txt"))
file.copy(file.path(out,"bundle/external-constraints.dcf"),file.path(bad,"external-constraints.dcf"),overwrite=TRUE)
target<-file.path(out,"must-not-be-created-corrupt")
stopifnot(!dir.exists(target))
status<-system2(rscript,c(shQuote(file.path(bad,"install.R")),shQuote(target),"win.binary"),stdout=file.path(out,"corrupt-preflight.log"),stderr=file.path(out,"corrupt-preflight.log"))
stopifnot(status!=0L,!dir.exists(target),any(grepl("checksum mismatch",readLines(file.path(out,"corrupt-preflight.log")))))
inventory[,"BinaryMD5"]<-unname(tools::md5sum(file.path(bad,"packages/r",inventory[,"Binary"])))
write.dcf(inventory,file.path(bad,"packages.dcf"))
writeLines("endomermissingdependencytest",file.path(bad,"external-dependencies.txt"))
target<-file.path(out,"must-not-be-created-dependency")
stopifnot(!dir.exists(target))
status<-system2(rscript,c(shQuote(file.path(bad,"install.R")),shQuote(target),"win.binary"),stdout=file.path(out,"dependency-preflight.log"),stderr=file.path(out,"dependency-preflight.log"))
stopifnot(status!=0L,!dir.exists(target),any(grepl("endomermissingdependencytest",readLines(file.path(out,"dependency-preflight.log")))))
writeLines(character(),file.path(bad,"external-dependencies.txt"))
write.dcf(data.frame(Package="jsonlite",Operator=">=",Required="999.0.0",RequestedBy="fixture"),file.path(bad,"external-constraints.dcf"))
target<-file.path(out,"must-not-be-created-version")
stopifnot(!dir.exists(target))
status<-system2(rscript,c(shQuote(file.path(bad,"install.R")),shQuote(target),"win.binary"),stdout=file.path(out,"version-preflight.log"),stderr=file.path(out,"version-preflight.log"))
stopifnot(status!=0L,!dir.exists(target),any(grepl("version does not satisfy",readLines(file.path(out,"version-preflight.log")))))
target<-file.path(out,"existing-library-fixture");dir.create(target,showWarnings=FALSE)
writeLines("retain existing contents",file.path(target,"sentinel.txt"))
before<-tools::md5sum(file.path(target,"sentinel.txt"))
status<-system2(rscript,c(shQuote(script),shQuote(target),"win.binary"),stdout=file.path(out,"existing-preflight.log"),stderr=file.path(out,"existing-preflight.log"))
stopifnot(status!=0L,identical(before,tools::md5sum(file.path(target,"sentinel.txt"))),
 identical(list.files(target),"sentinel.txt"),any(grepl("new or empty",readLines(file.path(out,"existing-preflight.log")))))
jsonlite::write_json(list(binary=TRUE,source=TRUE,corrupt_archive_rejected_before_write=TRUE,
 missing_dependency_rejected_before_write=TRUE,incompatible_dependency_rejected_before_write=TRUE,
 existing_library_preserved=TRUE),file.path(out,"bundle-install-audit.json"),auto_unbox=TRUE,pretty=TRUE)
